
// DEFINES.H

// PREPROCESOS
#define BASURA  1
#define GIRO	2
#define AJUSTAR 3

// CARACTERISTICAS
#define ZONING_4x3 1
#define ZONING_8x5 2
#define ZONING_13x8 3


/* ANADIR LOS DEFINES DE NUEVOS PREPROCESOS O CARACTERISTICAS */
